\i 'sql/create_tables/01_create_generations.sql'
\i 'sql/create_tables/02_create_pkmn_types.sql'
\i 'sql/create_tables/03_create_pokemon.sql'
\i 'sql/create_tables/04_create_moves.sql'
\i 'sql/create_tables/05_evos.sql'